name: LeetTest Action
author: Alfi Maulana
description: Compile and test solutions to LeetCode problems
branding:
  icon: zap
  color: black
inputs:
  path:
    description: Path of the directory to create
    required: true
runs:
  using: node20
  main: dist/index.js
