name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: threeal/setup-pnpm-action@v1.0.0

      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        uses: nick-fields/retry@v3.0.2
        with:
          timeout_minutes: 1
          max_attempts: 5
          command: pnpm build

      - name: Check Diff
        run: git diff && git diff-index --quiet --exit-code HEAD
