name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check-package:
    name: Check Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: latest

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: stable

      - name: Check Format
        run: |
          yarn format
          git diff --exit-code HEAD

      - name: Check Lint
        run: yarn lint

  test-action:
    name: Test Action
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout Solutions
        uses: actions/checkout@v4.1.2
        with:
          repository: threeal/leetspace-starter

      - name: Checkout Action
        uses: actions/checkout@v4.1.2
        with:
          path: leettest-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Test Solutions
        uses: ./leettest-action

  test-action-failure:
    name: Test Action Failure
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout Solutions
        uses: actions/checkout@v4.1.2
        with:
          repository: threeal/leetspace-starter

      - name: Modify Solutions
        run: echo "something" >> problems/2235/solution.cpp

      - name: Checkout Action
        uses: actions/checkout@v4.1.2
        with:
          path: leettest-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Test Solutions
        id: test-solutions
        continue-on-error: true
        uses: ./leettest-action

      - name: Test Solutions Should Be Failing
        run: exit ${{ steps.test-solutions.outcome == 'success' && '1' || '0' }}

  test-action-with-files-specified:
    name: Test Action With Files Specified
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout Solutions
        uses: actions/checkout@v4.1.2
        with:
          repository: threeal/leetspace-starter

      - name: Modify Solutions
        run: |
          cp -r problems/2235 problems/2236
          echo "something" >> problems/2235/solution.cpp

      - name: Checkout Action
        uses: actions/checkout@v4.1.2
        with:
          path: leettest-action
          sparse-checkout: |
            action.yml
            dist
          sparse-checkout-cone-mode: false

      - name: Test Solutions
        uses: ./leettest-action
        with:
          files: problems/2236/solution.cpp
